apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linux-logger
  name: linux-logger
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linux-logger
  template:
    metadata:
      labels:
        app: linux-logger
      name: linux-logger
    spec:
      containers:
        - name: linux-logger
          image: alpine:latest
          command:
              - /bin/echo
              - "ok"
      nodeSelector:
        kubernetes.io/os: linux
