  on:
    push:
      tags:
        - 'v[0-9]+.[0-9]+.[0-9]+'
  jobs:
    release:
      runs-on: windows-2022
      env:
        GH_TOKEN: ${{ github.token }}
      steps:
        - uses: actions/checkout@v1
        - name: Build
          run: go build -o rancher-powershell-utilities.exe
        - name: Create GH Release
          run: gh release create ${{ github.ref_name }} --verify-tag --generate-notes rancher-powershell-utilities.exe install.ps1
